#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriptdir}/_lib.sh"

import_dump() {
  eval mysql -h ${MYSQL_HOST} -u root \
    -p"${MYSQL_ROOT_PASSWORD}" "${MYSQL_NAME}" <"${1}"
}

dump="$(
  find "${HOME}/vol/dumps" -type f -regex ".*\.sql$" | sort |
    fzf --header "Please select a dump to import"
)"

rcmd import_dump "${dump}" || {
  echo -e "\033[0;91m[error]\033[0m importing dump failed, aborting"
  exit 1
}
rsql update_site_url
rsql enable_legacy_auth
rsql display_user_info
