#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriptdir}/_lib.sh"

mapfile -t arr < <(find "${HOME}/sql/init" -type f | sort)

for fil in "${arr[@]}"; do
  rcmd sql "${fil}" || {
    echo "an error occured"
    exit 1
  }
done
