#!/bin/bash

header() {
  echo -e "\n\033[0;33m${@}\033[0m"
}

rsql() {
  header "${1}"
  sql "${1}"
}

import_dump() {
  echo "import database: ${1}"
  eval mysql -h ${MYSQL_HOST} -u root \
    -p"${MYSQL_ROOT_PASSWORD}" "${MYSQL_NAME}" <"${1}"
}

mapfile -t arr < <(
  find "${HOME}/sql" -regex ".*\/init_.*\.sql" | sort
)

for fil in "${arr[@]}"; do
  sql "${fil}" || {
    echo "an error occured"
    exit 1
  }
done

dump="$(find "${HOME}/vol/dumps" -regex ".*\.sql$" | sort | tail -n 1)"

header "import dump ${dump}"
import_dump "${dump}"

rsql update_site_url
rsql enable_legacy_auth
rsql display_user_info
