#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriptdir}/_lib.sh"

installers_folder="${HOME}/installers"

detect() {
  if [[ -d "${installers_folder}" ]]; then
    find "${1}" -type f | grep "${2}" | sort | tail -n 1
  fi
}

dl() {
  url="${1}"
  target_file="${2}"
  target_folder="$(echo "${2}" | grep -Po ".*(?=\/)")"
  rcmd mkdir -p "${target_folder}" &&
    rcmd curl -so "${target_file}" "${url}"
}

extract_wp() {
  mkdir -p "${WORDPRESS_FOLDER}" &&
    tar xzf "${1}" -C "${WORDPRESS_FOLDER}" --strip-components=1
}

install() {
  installer="$(detect "${installers_folder}" "${1}")"
  ext="$(
    echo "${2}" | grep -Eo "[^/]+$" | grep -Eo "\.[a-z]+" | tr -d " \t\n\r"
  )"
  if [[ -z "${installer}" ]]; then
    echo "${1} installer not found, start to download"
    rcmd dl "${2}" "/tmp/${1}_latest${ext}"
    installer="$(detect "/tmp" "${1}")"
  fi
  if [[ -n "${installer}" ]]; then
    if [[ "${ext}" =~ gz$ ]]; then
      rcmd extract_wp "${installer}"
    else
      rcmd cp -f "${installer}" "${WORDPRESS_FOLDER}/"
    fi
  fi
}

# main
mkdir -p "${installers_folder}"

install wordpress https://wordpress.org/latest.tar.gz

install wp-cli \
  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
