#!/bin/bash

tempfile="/tmp/sql.tmp"

sql_file="${1}"
if [[ ! -f "${sql_file}" ]]; then
  sql_file="$(find "${HOME}/sql" | grep "${sql_file}" | sort | head -n 1)"
fi

if [[ -z "${sql_file}" ]]; then
  echo -e "\nplease pass arg defining sql file or use 'p' to enter sql db prompt"
  echo -e "usage: update_site_url update_site_url"
  exit
fi

export OLD_SITE_URL=$(
  mysql -h ${MYSQL_HOST} -u root -p${MYSQL_ROOT_PASSWORD} -c ${MYSQL_NAME} \
    -e "select option_value from wp_options where option_name='siteurl'" |
    tail -n 1
)

if [[ "${sql_file}" == "p" ]]; then
  mysql -h ${MYSQL_HOST} -u root -p${MYSQL_ROOT_PASSWORD} \
    -c "${MYSQL_NAME}"
else
  cat "${sql_file}" | envsubst >"${tempfile}"
  cat "${tempfile}"
  db_name_arg="-c ${MYSQL_NAME}"
  if [[ "${sql_file}" =~ .*\/init_create_db\.sql$ ]]; then
    db_name_arg=""
  fi
  mysql -h ${MYSQL_HOST} -u root -p${MYSQL_ROOT_PASSWORD} ${db_name_arg} \
    <"${tempfile}"
fi
