#!/bin/bash

tempfile="/tmp/sql.tmp"

sql_file="${1}"
if [[ ! -f "${sql_file}" ]]; then
  sql_file="$(find "${HOME}/sql" -type f | grep "${sql_file}" | sort | head -n 1)"
fi

if [[ -z "${sql_file}" ]]; then
  echo -e "\nplease pass arg defining sql file or use 'p' to enter sql db prompt"
  echo -e "usage: update_site_url update_site_url"
  exit
fi

cat "${sql_file}" | envsubst >"${tempfile}"

db_name_arg="-c ${MYSQL_NAME}"
if [[ "${sql_file}" =~ .*\/create_db\.sql$ ]]; then
  db_name_arg=""
fi

wait_for_db_up

mariadb --ssl=false -h ${MYSQL_HOST} -u root -p${MYSQL_ROOT_PASSWORD} ${db_name_arg} \
  <"${tempfile}"
