---
name: build

on:
  schedule:
    - cron: "0 37 * * 1,4"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual build test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install task
        env:
          URL: go-task/task
          GREP_SCHEME: linux_amd64.tar.gz
          TARGET_FOLDER: /home/runner/.local/bin
        run: curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/install_from_github.sh
          | bash
      - name: Install stoml
        env:
          URL: freshautomations/stoml
          GREP_SCHEME: linux_amd64
          TARGET_FOLDER: /home/runner/.local/bin
        run: curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/install_from_github.sh
          | bash && mv -f /home/runner/.local/bin/stoml* /home/runner/.local/bin/stoml
          && chmod +x /home/runner/.local/bin/stoml
      - name: Clone repo
        run: git clone https://github.com/triole/wordpress-dc.git
      - name: Init dummy config
        run: cp wordpress-dc/examples/conf.toml wordpress-dc/conf.toml
      - name: Task prep
        env:
          PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/.local/bin
        working-directory: wordpress-dc
        run: task prep
      - name: aasdas
        run: env | grep PATH
      - name: Build docker containers
        env:
          UID: 1000
          GID: 1000
          PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/.local/bin
        working-directory: wordpress-dc/docker
        run: task build
